aws:
  credentials:
    accessKey: ENC(LxQneopzsziJUOrfCou7gz/uQyTVOtopy3uger1Mr1Q=)
    secretKey: ENC(BfQ+yZMnjhRJ9McMGFpfHFLlfwPcVPT8c43sLhN0DqSeEv87mReauW0IHeUSubOsAcjf6VwVlO8=)
  queue: jg-sqs

jasypt:
  encryptor:
    password: h4i1707h3king