version: '2'
services:

  haproxy: 
    image: haproxy:1.7
    network_mode: host
    ports:
    - "8080:8080"
    - "9091:9091"
    volumes:
    - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg

  prometheus:
    image: prom/prometheus:v1.7.1
    network_mode: host
    ports:
      - "9090:9090"
    restart: always
    volumes: 
    - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:4.4.3
    network_mode: host
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - "./grafana:/var/lib/grafana"
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin