global:
  scrape_interval:     5s
  evaluation_interval: 5s

scrape_configs:

- job_name: app
  metrics_path: '/manage/prometheus'
  static_configs:
  - targets: [ 'localhost:9000', 'localhost:9001' ]